# Generated by Django 5.1.3 on 2025-03-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
